/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#303445",
        "on-primary-container": "#00533c",
        "on-error-container": "#ffdad6",
        "on-surface-variant": "#bacac1",
        "secondary": "#c3c6d8",
        "on-tertiary-fixed": "#301400",
        "on-error": "#690005",
        "inverse-primary": "#006c4f",
        "surface-container-high": "#25293a",
        "on-primary-fixed-variant": "#00513b",
        "on-secondary": "#2c303e",
        "on-tertiary-fixed-variant": "#713700",
        "inverse-on-surface": "#2b3040",
        "outline-variant": "#3c4a43",
        "surface": "#0e1322",
        "primary-fixed": "#59fdc5",
        "surface-container-lowest": "#090d1d",
        "inverse-surface": "#dee1f7",
        "primary": "#44edb7",
        "secondary-fixed": "#dfe1f5",
        "on-secondary-fixed-variant": "#424655",
        "primary-fixed-dim": "#2fe0aa",
        "surface-dim": "#0e1322",
        "secondary-container": "#454958",
        "tertiary": "#ffc8a3",
        "on-tertiary": "#502500",
        "surface-container-low": "#161b2b",
        "on-background": "#dee1f7",
        "error": "#ffb4ab",
        "surface-variant": "#303445",
        "surface-tint": "#2fe0aa",
        "outline": "#85948c",
        "tertiary-fixed-dim": "#ffb785",
        "background": "#0e1322",
        "tertiary-fixed": "#ffdcc6",
        "error-container": "#93000a",
        "on-tertiary-container": "#733800",
        "surface-bright": "#343949",
        "on-secondary-container": "#b4b7ca",
        "surface-container": "#1a1f2f",
        "secondary-fixed-dim": "#c3c6d8",
        "primary-container": "#00d09c",
        "on-primary-fixed": "#002116",
        "tertiary-container": "#ffa15b",
        "on-surface": "#dee1f7",
        "on-primary": "#003828",
        "on-secondary-fixed": "#171b29"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "20px",
        "container-max": "1440px",
        "md": "16px",
        "xl": "40px",
        "xs": "4px",
        "lg": "24px",
        "sm": "8px",
        "base": "4px"
      },
      fontFamily: {
        "label-mono": ["JetBrains Mono"],
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "title-md": ["Inter"],
        "display-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "caption": ["Inter"],
        "headline-md": ["Inter"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "label-mono": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "title-md": ["18px", { lineHeight: "24px", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "caption": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
