"""Alembic autogenerate script template."""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fd1470f3b40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_prefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('notify_new_nfo', sa.Boolean(), nullable=False),
    sa.Column('notify_news', sa.Boolean(), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_prefs_id'), 'notification_prefs', ['id'], unique=False)
    op.create_index(op.f('ix_notification_prefs_session_id'), 'notification_prefs', ['session_id'], unique=False)
    op.create_table('source_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('added_by', sa.String(length=100), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_source_urls_id'), 'source_urls', ['id'], unique=False)
    op.create_table('system_state',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('item_identifier', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_items_id'), 'watchlist_items', ['id'], unique=False)
    op.create_index(op.f('ix_watchlist_items_session_id'), 'watchlist_items', ['session_id'], unique=False)
    op.create_table('refresh_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_url_id', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_status', sa.String(length=20), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_url_id'], ['source_urls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_status_id'), 'refresh_status', ['id'], unique=False)
    op.create_table('scrape_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_url_id', sa.Integer(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('content_size', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['source_url_id'], ['source_urls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_history_id'), 'scrape_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scrape_history_id'), table_name='scrape_history')
    op.drop_table('scrape_history')
    op.drop_index(op.f('ix_refresh_status_id'), table_name='refresh_status')
    op.drop_table('refresh_status')
    op.drop_index(op.f('ix_watchlist_items_session_id'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_table('system_state')
    op.drop_index(op.f('ix_source_urls_id'), table_name='source_urls')
    op.drop_table('source_urls')
    op.drop_index(op.f('ix_notification_prefs_session_id'), table_name='notification_prefs')
    op.drop_index(op.f('ix_notification_prefs_id'), table_name='notification_prefs')
    op.drop_table('notification_prefs')
    # ### end Alembic commands ###
